export interface AutoGeneratedDetails {
  description: string;
  specifications: string[];
  suggestedSizes: string[];
  suggestedBrand?: string;
  suggestedModel?: string;
  suggestedType?: string;
}

export function generateShoeDetails(
  productName: string,
  currentBrand?: string,
  currentModel?: string,
  currentType?: string
): AutoGeneratedDetails {
  const nameLower = productName.toLowerCase();

  // Detect brand if not explicitly provided or generic
  let brand = currentBrand || 'E STORE';
  if (nameLower.includes('nike') || nameLower.includes('jordan') || nameLower.includes('air max') || nameLower.includes('air force')) brand = 'Nike';
  else if (nameLower.includes('adidas') || nameLower.includes('ultraboost') || nameLower.includes('yeezy') || nameLower.includes('stan smith')) brand = 'Adidas';
  else if (nameLower.includes('new balance') || nameLower.includes('nb 550') || nameLower.includes('nb 2002r') || nameLower.includes('nb 990')) brand = 'New Balance';
  else if (nameLower.includes('converse') || nameLower.includes('chuck') || nameLower.includes('all star')) brand = 'Converse';
  else if (nameLower.includes('vans') || nameLower.includes('old skool') || nameLower.includes('sk8') || nameLower.includes('checkerboard')) brand = 'Vans';

  // Detect shoe type & material characteristics
  let shoeCategory = currentModel || 'Sepatu Kasual / Lifestyle';
  let subType = currentType || 'Sneakers Low-top';
  let material = 'Premium Mesh & Leather Combination';
  let soleType = 'Durable Rubber Sole Anti-Slip';
  let usage = 'Aktivitas Harian, Hangout & Streetwear';

  if (nameLower.includes('run') || nameLower.includes('lari') || nameLower.includes('jogging') || nameLower.includes('zoom') || nameLower.includes('ultraboost')) {
    shoeCategory = 'Sepatu Olahraga';
    subType = 'Running Shoes';
    material = 'Breathable Knit & Light Mesh';
    soleType = 'Responsive Foam & High-Traction Rubber';
    usage = 'Lari Maraton, Jogging & Daily Running';
  } else if (nameLower.includes('basket') || nameLower.includes('jordan') || nameLower.includes('high-top') || nameLower.includes('high')) {
    shoeCategory = 'Sepatu Olahraga';
    subType = 'Basket';
    material = 'Full-Grain Leather & Ankle Support Padding';
    soleType = 'Air-Cushioned Traction Rubber';
    usage = 'Olahraga Basket & Fashion Streetwear';
  } else if (nameLower.includes('futsal') || nameLower.includes('bola') || nameLower.includes('cleats')) {
    shoeCategory = 'Sepatu Olahraga';
    subType = nameLower.includes('futsal') ? 'Futsal' : 'Bola';
    material = 'Synthetic Soft Touch Leather';
    soleType = 'Non-Marking Indoor Rubber Sole';
    usage = 'Pertandingan Futsal & Sepak Bola';
  } else if (nameLower.includes('hiking') || nameLower.includes('outdoor') || nameLower.includes('gunung')) {
    shoeCategory = 'Sepatu Olahraga';
    subType = 'Hiking';
    material = 'Water-Resistant Nubuck & Ripstop Textile';
    soleType = 'Vibram Grip Outdoor Lug Outsole';
    usage = 'Hiking, Trekking & Outdoor Adventure';
  } else if (nameLower.includes('loafer') || nameLower.includes('oxford') || nameLower.includes('derby') || nameLower.includes('monk') || nameLower.includes('formal') || nameLower.includes('pantofel')) {
    shoeCategory = 'Sepatu Formal & Semi-Formal';
    subType = nameLower.includes('loafer') ? 'Loafers' : nameLower.includes('monk') ? 'Monk Strap' : 'Oxford & Derby';
    material = 'Genuine Calfskin Leather Premium';
    soleType = 'Elegance Leather & Anti-Slip Rubber Cushion';
    usage = 'Acara Formal, Pernikahan & Kerja Kantoran';
  } else if (nameLower.includes('heels') || nameLower.includes('pump') || nameLower.includes('flat') || nameLower.includes('wedge') || nameLower.includes('ballerina') || nameLower.includes('stiletto') || nameLower.includes('wanita')) {
    shoeCategory = 'Sepatu Wanita';
    if (nameLower.includes('flat') || nameLower.includes('ballerina')) subType = 'Flat Shoes / Ballerina';
    else if (nameLower.includes('stiletto')) subType = 'Stiletto';
    else if (nameLower.includes('pump')) subType = 'Pumps';
    else if (nameLower.includes('wedge')) subType = 'Wedges';
    else subType = 'Kitten Heels';
    material = 'Soft Vegan Leather & Comfort Insole';
    soleType = 'Flexible Slip-Resistant Rubber';
    usage = 'Pesta, Acara Resmi, Kasual & Kerja';
  } else if (nameLower.includes('canvas') || nameLower.includes('kanvas') || nameLower.includes('vans') || nameLower.includes('converse')) {
    subType = 'Canvas Sneakers';
    material = 'Heavyweight 12oz Canvas';
    soleType = 'Vulcanized Waffle Rubber Sole';
  } else if (nameLower.includes('slip-on') || nameLower.includes('slip on')) {
    subType = 'Slip-on';
    material = 'Canvas & Elastic Side Panels';
  }

  const generatedName = productName.trim() || 'Sepatu E STORE Original';

  const description = `Sepatu ${generatedName} menghadirkan kombinasi sempurna antara estetika modern, durabilitas tinggi, dan kenyamanan maksimal sepanjang hari. Didesain secara presisi dengan material ${material.toLowerCase()} untuk memberikan sirkulasi udara yang baik serta ketahanan luar biasa. Dilengkapi dengan ${soleType.toLowerCase()} yang fleksibel dan meredam benturan di setiap langkah. Pilihan tepat untuk melengkapi gaya penampilan ${usage.toLowerCase()} Anda. 100% Produk Original di E STORE.`;

  const specifications = [
    `Brand: ${brand}`,
    `Bahan Upper: ${material}`,
    `Sol Luar (Outsole): ${soleType}`,
    `Insole: Memory Cushion Ergonomis (Empuk)`,
    `Penggunaan: ${usage}`,
    `Kualitas: 100% Original E STORE Guarantee`,
    `Garansi: Retur & Tukar Ukuran (Size Exchange) 3 Hari`
  ];

  const defaultSizes = ['38', '39', '40', '41', '42', '43', '44'];
  if (shoeCategory === 'Sepatu Wanita') {
    return {
      description,
      specifications,
      suggestedSizes: ['36', '37', '38', '39', '40'],
      suggestedBrand: brand,
      suggestedModel: shoeCategory,
      suggestedType: subType
    };
  }

  return {
    description,
    specifications,
    suggestedSizes: defaultSizes,
    suggestedBrand: brand,
    suggestedModel: shoeCategory,
    suggestedType: subType
  };
}
